### PR TITLE
Create shoot the monkey experiment

### PR DESCRIPTION
**Pull request by MarkMcGregor-dev**
This PR relates to the 3rd kinematics experiment, 'shooting the monkey', which demonstrates a bullet and a monkey falling at the same rate despite very different horizontal velocities.

### CODE REVIEW

**Review by PlumCantaloupe — COMMENTED** [review]
This all looks good, though there is still a "geometry buffer error" present (also present in the shootAndDrop world). I believe this is related to the desktop that no longer collides with the ball in the ShootAndDrop world.

A couple of notes is that it doesn't appear convincing that the ball hits the money. Seems to collide with monkey when it has hit the floor already. Maybe we need finder control of degrees/gravity - maybe incrementing and decrementing by something like 0.1 rather than larger deltas like 0.5? Also, the ball doesn't not collide with tree so it disappears inside its geometry ( I do love having that tree there :)

**Comment by PlumCantaloupe** [comment]
Added small change to explore view so that this world is also present in the list of worlds.

**Comment by TomasBabkine-DiCaprio** [comment]
@PlumCantaloupe.

Mark, Carly and I added finishing touches to the experiments! This should be good to go once you've reviewed it.

Let me know if you run into issues or bugs! :)

**Comment by PlumCantaloupe** [comment]
Looks great! I like how you re-organized the hub and everything looks to work well now. The whiteboards are also a nice touch. 

I will go ahead and merge this so we can get some feedback from the physics Prof. The only minor issues I noticed were that the shoot-and-drop worlds don't seem to show the same floor hit times when using higher gravitys. It would be nice to add some circles-sound and perhaps some circles-artefacts to help increase immersion, and lend more context and information around the purpose of the experiments. However, this is something that may be clearer after Prof. feedback.

Good work!

**Pull request merged**
