### PR TITLE
Island 3 including Tecum, Tegmentum, Red Nucleus scenes

### PR DESCRIPTION
**Pull request by judyc**
Includes Walter's changes and mine

Screen Shot 2022-02-23 at 1 29 54 PM

### CODE REVIEW

**Comment by PlumCantaloupe** [comment]
Okay thanks @judyc. I see we have so many "Memory_Palace_***" worlds (see screenshot below):

Screen Shot 2022-02-24 at 10 57 21 AM

Which ones should we keep? All of them? My understanding is that the "high resolution" version is probably not worth the effort as it doesn't work on the Oculus Quest anyhow.

Currently, I see that "COG_MemoryPalace_New" is the new world in this PR. Should we change the URL pathway here ( https://github.com/PlumCantaloupe/circlesxr/blob/b4c655f7b194570ac7f41eb5cf1acf9ae577496d/node_server/public/web/views/explore.pug#L21 ) to show the new world?

**Comment by judyc** [comment]
Hey Anthony,

Yep, the high resolution one can go. 

As for the LowRes (I think I see this more like production) and the "New" is like our staging environment that we're adding/developing to. 

Do you think it makes sense? We could remove the highres and rename the lowres as production and new as staging?

**Comment by judyc** [comment]
Is the cog-sci branch staging and main production?

**Comment by PlumCantaloupe** [comment]
Yeah, that makes sense. I currently have the cog-sci  branch circlesxr to show work to others but ultimately it should be main.

**Comment by PlumCantaloupe** [comment]
Okay, looks like it works. Tested on Quest and Chrome browser. Updated web links on explore page.

**Comment by PlumCantaloupe** [comment]
Also had to fix an naming issue where the uppercase "I" on "island_3/assets/FourMen.png" path was not consistent so the image would not load on Linux.

Make sure to use the same case for the pathway you give in A-Frame and in the file directories :)

**Pull request merged**
